### PR TITLE
Fix crash due to relationships with disbanded factions

### LINKED ISSUE #117: java.lang.NullPointerException
### Expected behavior

Idk, not crash

### Observed/actual behavior

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2024-10-22 20:39:34
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "io.icker.factions.api.persistents.Faction.getRelationship(java.util.UUID)" because the return value of "io.icker.factions.api.persistents.Faction.get(java.util.UUID)" is null
	at io.icker.factions.api.persistents.Faction.getReverse(Faction.java:230)
	at io.icker.factions.api.persistents.Faction.isMutualAllies(Faction.java:236)
	at io.icker.factions.api.persistents.Faction.lambda$getMutualAllies$4(Faction.java:240)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at io.icker.factions.api.persistents.Faction.getMutualAllies(Faction.java:240)
	at io.icker.factions.api.persistents.Faction.calculateMaxPower(Faction.java:312)
	at io.icker.factions.api.persistents.Faction.adjustPower(Faction.java:174)
	at io.icker.factions.core.FactionsManager.powerTick(FactionsManager.java:101)
	at io.icker.factions.api.events.PlayerEvents.lambda$static$12(PlayerEvents.java:98)
	at net.minecraft.class_3222.handler$bhi001$factions$tick(class_3222.java:10145)
	at net.minecraft.class_3222.method_5773(class_3222.java)
	at net.minecraft.class_3218.mixinextras$bridge$method_5773$219(class_3218.java)
	at net.minecraft.class_3218.wrapOperation$cgm000$puzzleslib$tickNonPassenger(class_3218.java:11797)
	at net.minecraft.class_3218.method_18762(class_3218.java:770)
	at net.minecraft.class_1937.method_18472(class_1937.java:498)
	at net.minecraft.class_3218.method_31420(class_3218.java:408)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:372)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
	at net.minecraft.class_3176.method_3813(class_3176.java:299)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at io.icker.factions.api.persistents.Faction.getReverse(Faction.java:230)
	at io.icker.factions.api.persistents.Faction.isMutualAllies(Faction.java:236)
	at io.icker.factions.api.persistents.Faction.lambda$getMutualAllies$4(Faction.java:240)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at io.icker.factions.api.persistents.Faction.getMutualAllies(Faction.java:240)
	at io.icker.factions.api.persistents.Faction.calculateMaxPower(Faction.java:312)
	at io.icker.factions.api.persistents.Faction.adjustPower(Faction.java:174)
	at io.icker.factions.core.FactionsManager.powerTick(FactionsManager.java:101)
	at io.icker.factions.api.events.PlayerEvents.lambda$static$12(PlayerEvents.java:98)
	at net.minecraft.class_3222.handler$bhi001$factions$tick(class_3222.java:10145)
	at net.minecraft.class_3222.method_5773(class_3222.java)
	at net.minecraft.class_3218.mixinextras$bridge$method_5773$219(class_3218.java)
	at net.minecraft.class_3218.wrapOperation$cgm000$puzzleslib$tickNonPassenger(class_3218.java:11797)
	at net.minecraft.class_3218.method_18762(class_3218.java:770)
	at net.minecraft.class_1937.method_18472(class_1937.java:498)
	at net.minecraft.class_3218.method_31420(class_3218.java:408)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 40
	Entity Name: X3nomji
	Entity's Exact location: 660.54, 197.00, 1035.15
	Entity's Block location: World: (660,197,1035), Section: (at 4,5,11 in 41,12,64; chunk contains blocks 656,-64,1024 to 671,319,1039), Region: (1,2; contains chunks 32,64 to 63,95, blocks 512,-64,1024 to 1023,319,1535)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:498)
	at net.minecraft.class_3218.method_31420(class_3218.java:408)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:372)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
	at net.minecraft.class_3176.method_3813(class_3176.java:299)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- Affected level --
Details:
	All players: 1 total; [class_3222['X3nomji'/40, l='ServerLevel[DanteWorld]', x=660.54, y=197.00, z=1035.15]]
	Chunk stats: 4090
	Level dimension: minecraft:overworld
	Level spawn location: World: (112,81,-832), Section: (at 0,1,0 in 7,5,-52; chunk contains blocks 112,-64,-832 to 127,319,-817), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,-64,-1024 to 511,319,-513)
	Level time: 36959522 game time, 41354880 day time
	Level name: DanteWorld
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Commands: false
	Level weather: Rain time: 82685 (now: false), thunder time: 80568 (now: false)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Loaded entity count: 131
Stacktrace:
	at net.minecraft.class_3218.method_8538(class_3218.java:1693)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1024)
	at net.minecraft.class_3176.method_3813(class_3176.java:299)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Linux (amd64) version 6.8.12-1-pve
	Java Version: 21.0.4, Ubuntu
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Ubuntu
	Memory: 245910336 bytes (234 MiB) / 1778384896 bytes (1696 MiB) up to 21474836480 bytes (20480 MiB)
	CPUs: 4
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 PRO 3400G with Radeon Vega Graphics
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: Zen / Zen+
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 3
	Number of logical CPUs: 4
	Graphics card #0 name: Picasso/Raven 2 [Radeon Vega Series / Radeon Vega Mobile Series]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MiB): 258.00
	Graphics card #0 deviceId: 0x15d8
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MiB): 19084.09
	Virtual memory used (MiB): 2345.64
	Swap memory total (MiB): 512.00
	Swap memory used (MiB): 0.00
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 12972.12, total: 30065.91
	Space in storage for workdir (MiB): available: 12972.12, total: 30065.91
	JVM Flags: 1 total; -Xmx20G
	Fabric Mods: 
		alternate-current: Alternate Current 1.9.0
		appleskin: AppleSkin 3.0.5+mc1.21
		architectury: Architectury 13.0.8
		balm-fabric: Balm 21.0.20
			kuma_api: KumaAPI 21.0.5-SNAPSHOT
		bclib: BCLib 21.0.13
		betterend: Better End 21.0.11
		betternether: Better Nether 21.0.11
		bettertridents: Better Tridents 21.0.1
		chunksending: Chunksending Mod 1.21-2.8
		cloth-config: Cloth Config v15 15.0.140
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 18.0.0.2
		collective: Collective 7.84
		comforts: Comforts 9.0.2+1.21.1
			cardinal-components-base: Cardinal Components API (base) 6.1.0
			cardinal-components-entity: Cardinal Components API (entities) 6.1.0
			spectrelib: SpectreLib 0.17.2+1.21
		connectedglass: Connected Glass 1.1.12
		connectivity: Connectivity Mod 1.21-5.8
		coroutil: CoroUtil 1.21.0-1.3.7
		craftingtweaks: Crafting Tweaks 21.1.2
		cristellib: Cristel Lib 1.2.8
			blue_endless_jankson: jankson 1.2.3
		cupboard: cupboard 1.21-2.7
		deathquotes: DeathQuotes 3.3
		debugify: Debugify 1.21+1.0
		dismountentity: Dismount Entity 3.5
		doubledoors: Double Doors 5.9
		easyanvils: Easy Anvils 21.0.5
		easymagic: Easy Magic 21.0.4
		emi: EMI 1.1.12+1.21+fabric
		emi_loot: EMI Loot 0.7.4+1.21+fabric
		entityculling: EntityCulling 1.7.0
		explorerscompass: Explorer's Compass 1.21-2.2.5-fabric
		fabric-api: Fabric API 0.102.0+1.21
			fabric-api-base: Fabric API Base 0.4.42+6573ed8cd1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd9d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.19+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.5.0+c5e2b5c6d1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.27+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.16+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.12+ba9dae06d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.4+78017270d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df360d1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209bd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+a551f7a4d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.12+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.2+60c3209bd1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b1d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+56599129d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.86+b5597344d1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.16+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+176f9036d1
		fabric-language-kotlin: Fabric Language Kotlin 1.12.3+kotlin.2.0.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.3
		fabricloader: Fabric Loader 0.16.5
			mixinextras: MixinExtras 0.4.1
		factions: Factions Mod 2.6.3
		ferritecore: FerriteCore 7.0.0
		forgeconfigapiport: Forge Config API Port 21.0.8
			com_electronwill_night-config_core: core 3.8.0
			com_electronwill_night-config_toml: toml 3.8.0
		framework: Framework 0.9.1
			org_javassist_javassist: javassist 3.29.2-GA
			org_reflections_reflections: reflections 0.10.2
		fusion: Fusion 1.1.1
		fzzy_config: Fzzy Config 0.5.4+1.21
			net_peanuuutz_tomlkt_tomlkt-jvm: tomlkt-jvm 0.3.7
		getittogetherdrops: Get It Together, Drops! fabric-1.21-1.3.1
		goldenhopper: Golden Hopper 1.5.3
		grindenchantments: Grind Enchantments 3.2.2+1.21-rc1
			codec-config-api: Codec config API 2.0.0+1.20.5-rc3
		inventorytotem: Inventory Totem 3.3
		jade: Jade 15.1.5+fabric
		java: OpenJDK 64-Bit Server VM 21
		journeymap: Journeymap 1.21-6.0.0-beta.27
			ar_com_hjg_pngj: pngj 2.1.0
			commonnetworking: Common Network 1.0.16-1.21
			journeymap-api-fabric: JourneyMap API 2.0.0-1.21-SNAPSHOT
		krypton: Krypton 0.2.8
			com_velocitypowered_velocity-native: velocity-native 3.3.0-SNAPSHOT
		letmedespawn: Let Me Despawn 1.3.2
		lithium: Lithium 0.13.1
		luckperms: LuckPerms 5.4.141
		mcwfurnitures: Macaw's Furniture 3.3.0
		mcwlights: Macaw's Lights and Lamps 1.1.1
		mcwpaths: Macaw's Paths and Pavings 1.0.5
		minecraft: Minecraft 1.21
		modernfix: ModernFix 5.19.1+mc1.21
		mr_dungeons_andtaverns: Dungeons and Taverns 1-v4.4.4
		naturescompass: Nature's Compass 1.21-2.2.6-fabric
		nerb: Not Enough Recipe Book 0.4.1
		netherportalfix: NetherPortalFix 21.0.2
		octolib: OctoLib 0.4.2
			org_yaml_snakeyaml: snakeyaml 2.2
		pickupnotifier: Pick Up Notifier 21.0.0
		placeholder-api: Placeholder API 2.4.1+1.21
		plasmovoice: Plasmo Voice 2.0.10
			aopalliance_aopalliance: aopalliance 1.0
			com_google_inject_guice: guice 5.0.1
			javax_inject_javax_inject: javax.inject 1
		puzzleslib: Puzzles Lib 21.0.28
		shulkerbox: Advanced Shulkerboxes 1.21.1-2.0.5
		shulkerboxtooltip: Shulker Box Tooltip 5.1.1+1.21
		smallships: Small Ships 2.0.0-b1.5
		smoothchunk: Smooth chunk save Mod 1.21-3.6
		sound_physics_remastered: Sound Physics Remastered 1.21.1-1.4.6
		stoneworks: Stoneworks 21.0.0
		structureessentials: Structure Essentials Mod 1.21-3.4
		styledplayerlist: Styled Player List 3.5.1+1.21
			fabric-permissions-api-v0: fabric-permissions-api 0.3.1
			player-data-api: Player Data API 0.6.0+1.21
			predicate-api: Predicate API 0.5.0+1.21
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.17+c
		t_and_t: Towns and Towers 1.13.2
		tectonic: Tectonic 2.4.1a
		terralith: Terralith 2.5.5
		treeharvester: Tree Harvester 9.1
		universalbonemeal: Universal Bone Meal 21.0.0
		veinmining: Vein Mining 5.0.0-beta+1.21
		visualworkbench: Visual Workbench 21.0.5
		watut: What Are They Up To 1.21.0-1.1.3
		wover: WorldWeaver 21.0.13
			wover-biome: WorldWeaver - Biome API 21.0.13
			wover-block: WorldWeaver - Block and Item API 21.0.13
			wover-common: WorldWeaver - Common API 21.0.13
			wover-core: WorldWeaver - Core API 21.0.13
			wover-datagen: WorldWeaver - Datagen API 21.0.13
			wover-events: WorldWeaver - Events API 21.0.13
			wover-feature: WorldWeaver - Feature API 21.0.13
			wover-generator: WorldWeaver - World Generator API 21.0.13
			wover-item: WorldWeaver - Item API 21.0.13
			wover-math: WorldWeaver - Math API 21.0.13
			wover-preset: WorldWeaver - World Preset API 21.0.13
			wover-recipe: WorldWeaver - Recipe API 21.0.13
			wover-structure: WorldWeaver - Structure API 21.0.13
			wover-surface: WorldWeaver - Surface API 21.0.13
			wover-tag: WorldWeaver - Tag API 21.0.13
			wover-ui: WorldWeaver - UI API 21.0.13
			wunderlib: WunderLib 21.0.8
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		yigd: You're in Grave Danger 2.4.11
			libgui: LibGui 11.0.0+1.21
				jankson: Jankson 8.0.0+j1.2.3
				libninepatch: LibNinePatch 1.2.0
	Server Running: true
	Player Count: 1 / 30; [class_3222['X3nomji'/40, l='ServerLevel[DanteWorld]', x=660.54, y=197.00, z=1035.15]]
	Active Data Packs: vanilla, fabric, balm-fabric (incompatible), bclib, betterend, betternether, bettertridents (incompatible), collective, comforts (incompatible), connectedglass (incompatible), craftingtweaks (incompatible), easyanvils (incompatible), easymagic (incompatible), emi_loot, explorerscompass, fabric-convention-tags-v2, goldenhopper (incompatible), mcwfurnitures (incompatible), mcwlights (incompatible), mcwpaths (incompatible), mr_dungeons_andtaverns, naturescompass, smallships, stoneworks (incompatible), supermartijn642corelib (incompatible), t_and_t, terralith, universalbonemeal (incompatible), veinmining (incompatible), visualworkbench (incompatible), wover-generator, wover-preset, wover-surface, wover-tag, yigd, tectonic:tectonic, bettertridents:boosted_impaling
	Available Data Packs: balm-fabric (incompatible), bclib, betterend, betterend:nourish_extensions, betterend:patchouli_extensions, betternether, betternether:vanilla-hammers_extensions, betternether:vanillaexcavators_extensions, bettertridents (incompatible), bettertridents:boosted_impaling, bundle, collective, comforts (incompatible), connectedglass (incompatible), craftingtweaks (incompatible), easyanvils (incompatible), easymagic (incompatible), emi_loot, explorerscompass, fabric, fabric-convention-tags-v2, goldenhopper (incompatible), mcwfurnitures (incompatible), mcwlights (incompatible), mcwpaths (incompatible), mr_dungeons_andtaverns, naturescompass, smallships, stoneworks (incompatible), supermartijn642corelib (incompatible), t_and_t, tectonic:tectonic, terralith, trade_rebalance, universalbonemeal (incompatible), vanilla, veinmining (incompatible), visualworkbench (incompatible), wover-generator, wover-preset, wover-surface, wover-tag, yigd
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	World Seed: -7757763600601063823
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

### Steps/models to reproduce

Idk I was just building a house

### Version

1.21

### Other

_No response_

### PR DESCRIPTION
**Pull request by xllifi**
Fixes #117

### CODE REVIEW

File: src/main/java/io/icker/factions/api/persistents/Faction.java [hunk 1]
```diff
@@ -224,7 +229,7 @@ public void setHome(Home home) {
     }
 
     public Relationship getRelationship(UUID target) {
-        return relationships.stream()
+        return this.getRelationships().stream()
```
Comment (BlueZeeKing) [inline src/main/java/io/icker/factions/api/persistents/Faction.java:232]: I don't think it is necessary to ensure all relationships are valid here because we can assume the faction being supplied does exist.

Comment (BlueZeeKing) [reply src/main/java/io/icker/factions/api/persistents/Faction.java:232]: It saves on a little performance to avoid the hash map lookup for each relationship, which is important because this may be run while ensuring interactions are allowed.

File: src/main/java/io/icker/factions/api/persistents/Faction.java [hunk 2]
```diff
@@ -84,6 +84,11 @@ public Faction(
 
     public Faction() {}
 
+    public ArrayList<Relationship> getRelationships() {
```
Comment (BlueZeeKing) [inline src/main/java/io/icker/factions/api/persistents/Faction.java:87]: Can this return a stream? It seems like every time it is used it is turned into a stream, so there is no reason to collect it back to a list.

**Review by BlueZeeKing — CHANGES_REQUESTED** [review]
